---
title: "Mini Project FA"
author: "S18827"
date: "2024-04-02"
output: pdf_document
---

```{r}
# Load necessary libraries
library(psych)  # for EFA
library(lavaan) # for CFA
```


```{r}
# Load the dataset
wine_data <- read.csv("winequality-red.csv")

# Check the structure of the dataset
str(wine_data)
```
```{r}
cor(wine_data)
#ghj
```


```{r}
# Perform Exploratory Factor Analysis (EFA)
efa_results <- fa(wine_data[, 1:11], nfactors = 3, rotate = "varimax")
print(efa_results)
```


```{r}
# Plot scree plot to determine the number of factors to retain
screeplot(efa_results)
```


```{r}
# Perform Confirmatory Factor Analysis (CFA)
# Define the CFA model
cfa_model <- '
  # Define latent factors
  quality =~ fixed_acidity + volatile_acidity + citric_acid + residual_sugar + chlorides + 
            free_sulfur_dioxide + total_sulfur_dioxide + density + pH + sulphates + alcohol
'

# Fit the CFA model
cfa_fit <- lavaan::cfa(cfa_model, data = wine_data)

# Summary of CFA model
summary(cfa_fit)

# Evaluate model fit indices
fit_indices <- fitMeasures(cfa_fit)
print(fit_indices)

```

